### PR TITLE
changing a variable

### PR DESCRIPTION
**Pull request by stevector**
Showing this repo to Paige and Erin. Feel free to close :)

### CODE REVIEW

**Comment by stevector** [comment]
@PumpPumper Have you tried Jupyter Notebooks? https://github.com/blog/1995-github-jupyter-notebooks-3

**Comment by PumpPumper** [comment]
Hey! Nope. Never tried Jupyter. But I'll give it a try. What would you say are the big advantages of Jupyter?

**Comment by stevector** [comment]
My understanding of the value of Jupyter Notebooks is that they are designed to mix text and python (or other language) output. Here is an example with plotting: https://github.com/ipython/ipython/blob/master/examples/IPython%20Kernel/Plotting%20in%20the%20Notebook.ipynb

So I think you could write a paper in a Notebook and have all of your charts/figures be embedded and render in real time.

**Comment by stevector** [comment]
I saw some tweets yesterday coming out of NICAR (a journalism conference) about this presentation covering Python tribal knowledge. It mentions Jupyter Notebooks: https://docs.google.com/presentation/d/1fWNZdPzdaKSzNhPo0ZnUGqs-PSiTaNJ_CBP4ZmdgssY/edit#slide=id.g2108425a6a_0_289

**Comment by PumpPumper** [comment]
Thanks. Jupyter Notebooks look pretty cool. I need to play around with
them. I learned a couple other things from that presentation too. I'm gonna
check out the virtual environments.

**Pull request merged**
